name: wholesome_cli
description: A Command Line Tool for Flutter Projects. 
# version: 1.0.0
# homepage: https://wholesome.clawstudios.com/
# author: Claw Studios <info@clawstudios.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
